name: FIA -> Instagram hourly
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}
jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install system deps (poppler)
        run: sudo apt-get update && sudo apt-get install -y poppler-utils
      - name: Install pip deps
        run: python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Run bot
        env:
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_BRANCH: 'main'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIA_BASE_URL: ${{ secrets.FIA_BASE_URL }}
          PDF_SEARCH_KEYWORD: ${{ secrets.PDF_SEARCH_KEYWORD }}
          GITHUB_COMMITTER_NAME: 'fia-bot'
          GITHUB_COMMITTER_EMAIL: 'fia-bot@example.com'
        run: |
          python fia_instagram_bot.py
